<div class="panel panel-info">
    <div class="panel-heading">
        <h3>Hoeveel krijg jij? <a class="btn" href="#" data-toggle="collapse" data-target="#collapse-txt"><span class="small">lees meer...</span> <span class="caret"></span></a></h3>
    </div>
    <div id="collapse-txt" class="collapse">
        <div class="panel-body">
            <p>
                Binnen een paar minuten reken je hier geheel vrijblijvend uit hoeveel geld je van de
                belastingdienst kunt terugkrijgen.
                Als je geld kunt terugkrijgen, kun je tegen geringe kosten
                <span class="info-tooltip" title="Om deze website (met gratis rekenmodule) voor iedereen beschikbaar te houden, vragen wij een vergoeding van 10% van jou teruggave, maar nooit meer dan &euro;&nbsp;20,00."> <span class="glyphicon glyphicon-info-sign"></span></span>
                direct de teruggave laten regelen.
                Het enige wat je bij de hand moet hebben is een jaaropgave of loonstrook.
            </p>
            <p>Gemiddeld vragen wij voor onze klanten zo'n &euro;&nbsp;270,39 terug bij de Belastingdienst.</p>
            <div class="dropup pull-right">
                <a class="btn" href="#" data-toggle="collapse" data-target="#collapse-txt"> <span class="caret"></span> </a>
            </div>
        </div>
    </div>
</div>

<div id="aangifte-panel" class="panel panel-warning">
    <div class="panel-heading">
        <h4>1/5 - <?php echo $view['title'] ?></h4>
    </div>
    <div class="panel-body">
        <?php if ($this->hasMessage($script)): ?>
            <div class="alert alert-warning alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo $this->getMessage($script) ?>
            </div>
        <?php endif; ?>
<?php
