<?php if ($view['aangifte']->extrakosten): ?>
    <h4 class="data-overview">Aftrekposten</h4>
    <div class="table-responsive">

        <?php if (count($view['aangifte']->ziektekosten)): ?>
            <table class="table">
                <thead>
                    <tr>
                        <th colspan="2">Ziektekosten</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($view['aangifte']->ziektekosten as $post): ?>
                        <?php if (!empty($post['omschrijving'])): ?>
                            <tr>
                                <td style="text-align: left;"><?php echo $post['omschrijving'] ?>&nbsp;</td>
                                <td style="text-align: right;">&euro;&nbsp;<?php echo $post['bedrag'] ?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach ?>
                </tbody>
            </table>
        <?php endif; ?>

        <?php if (count($view['aangifte']->studiekosten)): ?>
            <table class="table">
                <thead>
                    <tr>
                        <th colspan="2">Studiekosten</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($view['aangifte']->studiekosten as $post): ?>
                        <?php if (!empty($post['omschrijving'])): ?>
                            <tr>
                                <td style="text-align: left;"><?php echo $post['omschrijving'] ?>&nbsp;</td>
                                <td style="text-align: right;">&euro;&nbsp;<?php echo $post['bedrag'] ?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>

    <?php

 endif;
