<?php
$this->render('page-header', $view, 'partials');
$this->render('aangifte-header', $view);
?>
<p class="question">Klopt onderstaande voor jou? Vink uit wat niet van toepassing is.</p>
<hr>
<form action="?action=aangifte&check" method="post">
    <input type="hidden" name="csrf" value="<?php echo $view['csrf'] ?>" />
    <div class="panel panel-warning">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="check[student]" value="1" checked="checked">
                            Ik was in <?php echo $view['aangifte']->jaar ?> scholier/student en jonger dan 30 jaar.
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-warning">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="check[inkomen]" value="1" checked="checked">
                            Ik heb in <?php echo $view['aangifte']->jaar ?> niet meer dan &euro; 18.000,- verdiend.
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-warning">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="check[opgave]" value="1" checked="checked">
                            Ik heb mijn jaaropgave of loonstrook december van <?php echo $view['aangifte']->jaar ?> bij de hand.
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
	<hr>
    <div class="form-group prev-next">
        <a class="btn btn-default" href="?action=aangifte&check&prev">Terug</a>
        <button type="submit" class="btn btn-warning pull-right"><span class="glyphicon glyphicon-ok"></span> Volgende</button>
    </div>
</form>
<?php
$this->render('aangifte-footer', $view);
$this->render('page-footer', $view, 'partials');
