<?php $this->render('page-header', $view, 'partials') ?>

    <div class="alert">
        <h3>Geen probleem als je de jaaropgave niet bij de hand hebt.</h3>
        <hr>
        <p>Neem contact op met de afdeling personeelszaken van je werkgever en vraag de jaaropgave op. Je krijgt deze per post opgestuurd.</p>
        <p>Keer daarna terug op <a class="btn btn-default btn-xs" href="http://hoeveelkrijgjij.nl">hoeveelkrijgjij.nl</a> en maak je aanvraag compleet.</p>
        <br>
        <h4>Dan heb je binnen no-time je geld.</h4>
    </div>

<?php //include 'views/partials/add-this.phtml';
$this->render('page-footer', $view, 'partials');
