<div class="table-responsive col-sm-offset-3">
    <h3>Ziektekosten</h3>
    <table>
        <thead>
            <tr>
                <th>Omschrijving</th><th>Bedrag</th>
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 1; $i <= 5; $i++): ?>
                <?php
                $omschrijving = isset($view['aangifte']->ziektekosten[$i]['omschrijving']) ? $view['aangifte']->ziektekosten[$i]['omschrijving'] : '';
                $bedrag = isset($view['aangifte']->ziektekosten[$i]['bedrag']) ? $view['aangifte']->ziektekosten[$i]['bedrag'] : '';
                ?>
                <tr>
                    <td style="width: 70%;">
                        <input type="text" name="ziektekosten[<?php echo $i ?>][omschrijving]" value="<?php echo $omschrijving ?>" class="form-control" >
                    </td>
                    <td style="width: 30%;">
                        <input type="text" name="ziektekosten[<?php echo $i ?>][bedrag]"  value="<?php echo $bedrag ?>" class="form-control" ></td>
                </tr>
            <?php endfor; ?>
        </tbody>
    </table>
</div>
