<div class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
<!--                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>-->
                <a class="navbar-brand" href="http://hoeveelkrijgjij.nl" title="Naar homepage Hoeveelkrijgjij.nl" target="_blank"><img height="32px" src="img/hoeveelkrijgjij-logo-tekst.png"></a>
                <!--<a class="navbar-brand visible-xs visible-sm active" href="http://hoeveelkrijgjij.nl/aangifte-doen/"><em>Check je teruggave</em></a>-->
                <p class="navbar-text">Eenvoudig loonheffing terugvragen</p>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav nav-pills">
                    <!--<li class="visible-md visible-lg active"><a href="?=aangifte">Check je teruggave</a></li>-->
                </ul>
            </div>
        </div>
    </nav>
</div>
