<!DOCTYPE html>
<html>
    <head>

		<meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>&#128182; Regel eenvoudig je Belastingteruggave! | Hoeveelkrijgjij.nl</title>
		<meta name="description" content="Je belastingteruggave berekenen en regelen in enkele eenvoudige stappen. Hoeveelkrijgjij.nl helpt jongeren bij het doen van hun belastingaangifte.">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans" type="text/css">
        <link rel="stylesheet" href="bootstrap/css/bootstrap.css" type="text/css"/>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="bootstrap/css/bootstrap-theme.css" type="text/css"/>
        <link rel="stylesheet" href="./css/style.css" type="text/css"/>
        <script type="text/javascript" src="./js/jquery.js"></script>
        <script type="text/javascript" src="./bootstrap/js/bootstrap.js"></script>
        <script type="text/javascript" src="./js/jquery.metadata.js"></script>
        <script type="text/javascript" src="./js/jquery.validate.js"></script>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5106f1132745b72b" async="async"></script>
        <script type="text/javascript">
            $(function() {
                $('.info-tooltip').tooltip();

                $.metadata.setType('attr', 'validate');
                $('#form1').validate();
            });
        </script>

		<!--Start of Zopim Live Chat Script-->
		<script type="text/javascript">
		window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
		d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
		_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
		$.src='//v2.zopim.com/?2jhvRccosJfw7n8U55yjy7rGctgHeRXp';z.t=+new Date;$.
		type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
		</script>
		<!--End of Zopim Live Chat Script-->
        <?php $this->render('gtm-datalayer', $view, 'partials'); ?>
		

    </head>
    <body>
        <?php $this->render('gtm-source', $view, 'partials'); ?>
        <?php include 'navbar.phtml'; ?>
        <div class="container">
            <div class="row">