<?php if ($view['aangifte']->extrakosten): ?>
    <h4 style="margin-top: 0;margin-bottom: 10px;">Aftrekposten</h4>
    <?php if (count($view['aangifte']->ziektekosten)): ?>
        <table style="margin: 0px auto; width: 80%;color: #505050;font-family: Helvetica;font-size: 13px;line-height: 200%;">
            <thead>
                <tr>
                    <th colspan="2" style="border-bottom: 1px solid #e0e0e0;text-align: left;width: 20%;font-size: 11px;border-collapse: collapse;">Ziektekosten</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($view['aangifte']->ziektekosten as $post): ?>
                    <?php if (!empty($post['omschrijving'])): ?>
                        <tr>
                            <td  style="text-align: left;border-collapse: collapse;"><?php echo $post['omschrijving'] ?></td>
                            <td style="text-align: right;border-collapse: collapse;">&euro;&nbsp;<?php echo $post['bedrag'] ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>

    <?php if (count($view['aangifte']->studiekosten)): ?>
        <table style="margin: 0px auto; width: 80%;color: #505050;font-family: Helvetica;font-size: 13px;line-height: 200%;">
            <thead>
                <tr>
                    <th colspan="2" style="border-bottom: 1px solid #e0e0e0;text-align: left;width: 20%;font-size: 11px;border-collapse: collapse;">Studiekosten</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($view['aangifte']->studiekosten as $post): ?>
                    <?php if (!empty($post['omschrijving'])): ?>
                        <tr>
                            <td style="text-align: left;border-collapse: collapse;"><?php echo $post['omschrijving'] ?>&nbsp;</td>
                            <td style="text-align: right;border-collapse: collapse;">&euro;&nbsp;<?php echo $post['bedrag'] ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach ?>
            </tbody>
        </table>
    <?php
    endif;
 endif;
