<h4 style="margin-top: 0;margin-bottom: 10px;">Overzicht jaaropgave(n)</h4>
<table style="margin: 0px auto; width: 80%;color: #505050;font-family: Helvetica;font-size: 13px;line-height: 200%;">
    <thead>
        <tr>
            <th style="border-bottom: 1px solid #e0e0e0;text-align: left;width: 20%;font-size: 11px;border-collapse: collapse;">Werkgever</th>
            <th style="border-bottom: 1px solid #e0e0e0;text-align: right;width: 10%;font-size: 11px;border-collapse: collapse;">Brutoloon</th>
            <th style="border-bottom: 1px solid #e0e0e0;text-align: right;width: 10%;font-size: 11px;border-collapse: collapse;">Loonheffing</th>
            <th style="border-bottom: 1px solid #e0e0e0;text-align: right;width: 10%;font-size: 11px;border-collapse: collapse;">Arbeidskorting</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($view['aangifte']->opgaves as $opgave): ?>
        <tr style='border-bottom: 1px;'>
            <td style="text-align: left;border-collapse: collapse;"><strong><?php echo $opgave->werkgever ?></strong> &nbsp;</td>
            <td style="text-align: right;border-collapse: collapse;">&euro;&nbsp;<?php echo number_format($opgave->salaris, 2, ',', '.') ?></td>
            <td style="text-align: right;border-collapse: collapse;">&euro;&nbsp;<?php echo number_format($opgave->loonheffing, 2, ',', '.') ?></td>
            <td style="text-align: right;border-collapse: collapse;">&euro;&nbsp;<?php echo number_format($opgave->arbeidskorting, 2, ',', '.') ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
